





    <script>
        $(document).ready(function() {
            $("table").addClass("table-hover bg-white table-sm table-bordered")
            $("#cantidad").tablesorter({
                widgets: ['zebra'],
                sortList: [
                    [1, 0]
                ],
            });
        });
    </script>



    <div class="my-4">
        <?php
        cardtitulo("Conteo de productos");
        ?>
    </div>

    <div class="col-md-4 p-2 mx-auto my-4 ">
        <table id="example" class=" border-arriba tablesorter table table-bordered  table-striped bg-white table-sm mx-auto text-center">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Stok</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                <?php

                foreach ($this->datos[0] as $i => $row) {
                    $p  =  $row[1];
                    $c = "text";
                    if ($p < 2) {
                        $c = "danger"; $m = "Producto agotado";
                    } elseif ($p <= 6) {
                        $c = "warning"; $m = "Existencia baja";
                    } elseif ($p >= 7) {
                        $c = "success"; $m = "Suficiente";
                    }
                    $c = "bg-" . $c;
                ?>
                    <tr>
                        <td> <?= $row['nom_prod']  ?></td>
                        <td title="<?= $m ?>" class="<?='text-white '.$c ?>"><strong> <?= $row['total']  ?> </strong> </td>
                        <td><?= $m ?></td>
                    </tr>
                 
                   
               

                <?php    }  ?>
            </tbody>
            <tr>
               <td><strong>Total de productos</strong> </td>
               <td><?= $this->datos[1] ?></td>
            </tr>
        </table>
    </div><!-- fin de div tabla responce -->

