<?php
cardtitulo("Informe de Facturcion");
?>
<div class="card card-body box-card text-center col-md-10 col-lg-6 col-12 mx-auto">
    <!--<div class="container">-->
    <div class=" container-fluid ">
        <div class="card card-body  shadow-lg ">
        
        <form method="POST">
            <div class="row">
                <div class="col-md-6">
                    <!-- derecha -->
                    <label for="start">Fecha inicial:</label>
                    <div class="form-group"><input class="form-control" type="date" id="start" name="f1" value="2015-01-01" min="0000-00-00" max="9999-99-99"></div>
                    <label for="start">Fecha fin:</label>
                    <div class="form-group"><input class="form-control" type="date" id="start" name="f2" value="<?= date('Y-m-d') ?>"></div>
                </div><!-- fin primera columna de 6 -->



                <div class="col-md-6">
                    <!-- Izquierda -->
                    Formato de descarga <br>
                    <select name="formato" class="form-control">
                    
<?php
foreach( [ 'CSV', 'EXCEL', 'PDF', 'XML'  ]  as $i => $d){
    echo   '<option '.((isset($_POST['formato'])) && ($_POST['formato'] == $i) ? 'selected': '').'  value="'. $i .'">'.$d.'</option>';
}
?>
                    </select><br>

                    <div class="form-group"> <input class="btn btn-primary form-control" type="submit" value="Ver informe" name="consulta"> </div>
        </form>
        <a class="btn btn-block btn-primary my-2" href="">Imprimir informe</a>
    </div><!-- fin de segunda columna de 6 -->
    </div>

</div><!-- fin de row -->
</div><!-- fin de container fluid -->
</div><!-- fin de card -->

<?php
/*
if (isset($_POST['consulta'])) {
    extract($_POST);
    $facturas    = $objModFact->verIntervaloFecha($f1, $f2);

  */


if (isset($this->facturas)) {
?>


    <div class="container">
        <div class="my-4">
            <div class="row">
                <table id="facturas" class="bg-white col-md-10 col-sm-12 col-xs-12 mx-auto">
                    <thead class="bg-dark text-white text-center">
                        <tr>
                            <th><i></i> fecha</th>
                            <th><i></i> Nombre de cliente</th>
                            <th><i></i> Medio de pago</th>
                            <th><i></i> Iva</th>
                            <th><i></i> total</th>
                            <th><i></i> Factura No.</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php

                        foreach ($this->facturas['response_msg'][0] as $i => $d) {

                        ?>

                            <tr>
                                <td><?= $d[8] ?></td>
                                <td><?= $d[2] . ' ' . $d[3] . ' ' . $d[4] . ' ' . $d[5] ?> </td>
                                <td><?= $d[10] ?></td>
                                <td><?= ('$' . number_format(($d[11] * 0.19), 0, ',', '.'))  ?></td>

                                <td><?= '$' . number_format($d[11], 0, ',', '.');  ?></td>
                                <td class= "text-center mx-auto" >
                                        <button href="" class="btn btn-circle btn-success btn" 
                                        data-bs-toggle="tooltip" data-bs-placement="right" title="Consultar factura" 
                                        type="submit" name="f" 
                                        href="javascript:void(0)" 
                                        onclick="PopupCenter('<?= BASE_URL . 'supervisor/consulta?f='.$d[7] ?>','Sicloud-detalle','1000','1000');">
                                        <?= $d[7] ?> </i>
                                        </button>
                                        <input type="hidden" name="accion" value="consFactura">
                                </td>
                            </tr>
            
                <?php
                        }
                ?>
                <tr>
                </tbody>
                    <td colspan="3" class="mt-2 lead" align="right">
                        Total
                    </td>

                    <td colspan="2" class="mt-2 lead" align="right">
                    <?php
$total       =  
$v = new c_numerosLetras;
$letra = ($v->convertirEurosEnLetras( $this->facturas['response_msg'][1] ));
                    ?>
                        <?= '$' . number_format($this->facturas['response_msg'][1], 0, ',', '.');  ?>
                    <td></td>
                    </td>
                </tr>
                <tr>
                    <td class="bg-dark text-white" colspan="6">
                        <em><?= ucfirst($letra); ?></em>
                    </td>
                </tr>

                </table>
            </div>
        </div>
    </div>


<?php
}
?>