<?php
cardtitulo("Informe de Facturcion");
?>
<div class="card card-body box-card text-center col-md-10 col-lg-6 col-12 mx-auto">
    <!--<div class="container">-->
    <div class=" container-fluid ">
        <div class="card card-body  shadow-lg ">
        
        <form method="POST">
            <div class="row">
                <div class="col-md-6">
                    <!-- derecha -->
                    <label for="start">Fecha inicial:</label>
                    <div class="form-group"><input class="form-control" type="date" id="start" name="f1" value="2015-01-01" min="0000-00-00" max="9999-99-99"></div>
                 </div> 

                   <div class="col-md-6"> 
                        <label for="start">Fecha fin:</label>
                        <div class="form-group"><input class="form-control" type="date" id="start" name="f2" value="<?= date('Y-m-d') ?>"></div>
                    </div> 
            </div><!-- fin primera columna de 6 -->
       

         <div class="row">
                <div class="col-md-6 mx-auto">
                    <!-- derecha -->
                    <div class="form-group"> <input class="btn btn-primary form-control" type="submit" value="Ver informe" name="consulta"></div>
                </div><!-- fin primera columna de 6 -->
         </div>


                
        </form>

    </div><!-- fin de segunda columna de 6 -->
    </div>

</div><!-- fin de row -->
<?php

if (isset($this->facturas ) && ( $this->facturas['response_status'] =='ok'   )) {
?>


<div class="container">
        <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">        
                        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead class="bg-dark text-white text-center">
                        <tr>
                            <th> fecha</th>
                            <th> Nombre de cliente</th>
                            <th> Medio de pago</th>
                            <th> Iva</th>
                            <th> total</th>
                            <th> Factura No.</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php

              foreach ($this->facturas['response_msg'][0] as $i => $d) {

                        ?>

                            <tr>
                                <td><?= $d[8] ?></td>
                                <td><?= $d[2] . ' ' . $d[3] . ' ' . $d[4] . ' ' . $d[5] ?> </td>
                                <td><?= $d[10] ?></td>
                                <td><?= ('$' . number_format(($d[11] * 0.19), 0, ',', '.'))  ?></td>

                                <td><?= '$' . number_format($d[11], 0, ',', '.');  ?></td>
                                <td class= "text-center mx-auto" >
                                        <button href="" class="btn btn-circle btn-success btn" 
                                        data-bs-toggle="tooltip" data-bs-placement="right" title="Consultar factura" 
                                        type="submit" name="f" 
                                        href="javascript:void(0)" 
                                        onclick="PopupCenter('<?= BASE_URL . 'supervisor/consulta?f='.$d[7] ?>','Sicloud-detalle','1000','1000');">
                                        <?= $d[7] ?> </i>
                                        </button>
                                        <input type="hidden" name="accion" value="consFactura">
                                </td>
                            </tr>
            
                <?php
                        }
                ?>              
                        </tbody>        
                       </table>                  
                    </div>
                </div>
        </div>  
    </div>   
    <?php
}else{
   
 if( isset($this->facturas)){
  echo'<div class="alert text-center col-md-4 mx-auto alert-info alert-dismissible fade show" role="alert">
'.$this->facturas['response_msg'].'      
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true"></span>
</button>
</div>';
}

}

?>
<?php
/*
if (isset($_POST['consulta'])) {
    extract($_POST);
    $facturas    = $objModFact->verIntervaloFecha($f1, $f2);

  */
