<?php
cardtituloS("Administrador de solicitiudes");
?>

<script>
    function desactivarCuenta(id_to_delete) {
        var confirmation = confirm('Esta seguro que desea desactivar: ' + id_to_delete + ' ?');
        if (confirmation) {
            window.location = "<?= BASE_URL ?>admin/d/" + id_to_delete;
        }
    }
</script>
<script>
    function activarCuenta(id_to_delete) {
        var confirmation = confirm('Esta seguro que desea activar: ' + id_to_delete + ' ?');
        if (confirmation) {
            window.location = "<?= BASE_URL ?>admin/a/" + id_to_delete;
        }
    }
</script>
<div class="card card-body my-4 col-lg-2 mx-auto">
    <button class="btn btn-primary toggle" id="">Buscar Usuario</button>
</div>
<div class="card card-body col-md-8 mx-auto my-2 text-center form">
    <div class="card-title ">Filtros</div>
    <div class="row">
        <!-- Primera fila  4 de 12 col-->
        <div class="card card-body col-md-4 shadow ">
            <h6>Busqueda por Usuario</h6>
            <div class="card card-body mx-auto col-10 my-2 shadow border">
                <!-- form por id -->
                <form action="<?= BASE_URL ?>admin/consulta" method="POST">
                    <div class="form-group"><input type="text" class="form-control " placeholder="Identidad" name="documento" onChange="submit(this)"
                    value="<?= (( isset($_POST['documento']) &&  $_POST['documento'])?  $_POST['documento']:'') ?>"></div>
                    <input type="hidden" value="bId" name="accion">
                </form>
                <!-- fin de form por id -->
            </div><!-- fin de card -->
        </div><!-- fin de primera divicion -->
        <!-- -------------------------------------------------------------- -->

        <!-- Segunda fila 8 de  12 col-->
        <div class="card card-body col-md-4 shadow">
            <h6>Busqueda por Estado de cuenta</h6>
            <div class="card card-body mx-auto col-10 my-2 shadow border">
                <form action="<?= BASE_URL ?>admin/consulta" method="POST">
                    <div class="form-group">
                        <select name="estado" class="form-control " onChange="submit(this)">
                            <?php
                                echo '<option ' . (( !isset( $_POST['estado'] )) ? ' selected' : '' ) . 'disable=""  value=""> -- Seleccione -- </option>';
                            foreach ($this->datosFijos[4]  as $i => $d) {
                                echo '<option ' . (( $_POST['estado'] != '' &&  $_POST['estado']  == $i) ? ' selected' : '') . ' value="' . $i . '">' . $d . '</option>';
                            }
                            ?>
                        </select>
                    </div>

                    <input type="hidden" value="estado" name="accion">
                </form><!-- fin de form estado filtro estado de cuenta -->
            </div><!-- fin de card -->
        </div><!-- fin de segundsa divicion -->
        <!-- -------------------------------------------------------------- -->
        <!-- Tercera fila 12 de 12 col bootstrap-->
        <div class="card card-body col-md-4 shadow">
            <h6>Busqueda por rol</h6>
            <div class="card card-body mx-auto col-10 my-2 shadow border">
                <!-- formulario de filtro por rol -->
                <form action="<?= BASE_URL ?>admin/consulta" method="POST">
                    <div class="form-group">

                        <select name="rol" class="form-control " onChange="submit(this)">
                            <?php
                                 echo '<option ' . (( !isset( $_POST['rol'] )) ? ' selected' : '') . ' value=""> -- Seleccione -- </option>';
                            foreach ($this->datosFijos[0]  as $i => $d) {
                                echo '<option ' . (($_POST['rol']  == $i) ? ' selected' : '') . ' value="' . $i . '">' . $d . '</option>';
                            }
                            ?>
                        </select>
                    </div>
                    <input type="hidden" name="accion" value="consRol">
                </form><!-- fin form ver por rol -->
            </div><!-- fin de card -->
        </div><!-- fin de tercera divicion -->

        <!-- -------------------------------------------------------------- -->
    </div><!-- fin de row -->
</div>

<?php
if (isset($_SESSION['message'])) {  ?>
    <!-- alerta boostrap -->
    <div class="alert text-center col-md-4 mx-auto alert-<?= $_SESSION['color']   ?> alert-dismissible fade show" role="alert">
        <?= $_SESSION['message']  ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php
    setMessage();
}

if (isset($this->tabla) &&  $this->tabla['response_status'] == 'ok') {
?>
    <div class="col-lg-12">
        <div class="table-responsive">
            <table id="lis" style="width:100%" class="bg-white">
                <thead>
                    <tr>
                        <th>Foto</th>
                        <th>Tipo doc</th>
                        <th> <i></i> Documento</th>
                        <th><i></i>Nombres</th>
                        <th><i></i>Apellidos</th>
                        <th><i></i>Rol</th>
                        <th><i></i>Correo</th>
                        <th><i></i>Estado</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->tabla['response_msg'] as $i  => $d) {
                    ?>

                        <tr>
                            <!-- Los nombres que estan en [''] son los mismos de los atributos de la base de datos de lo contrario dara un error -->
                            <td><img class="img-profile ml-3 rounded-circle mx-auto" src=" <?= RUTAS_APP['ruta_img'] . 'us/' . (($d['foto'] != '') ? $d['foto'] : imgUsuario)  ?>" alt="Card image cap" height="65" width="70"></td>
                            <td><?= $d['FK_tipo_doc'] ?></td>
                            <td><?= $d['ID_us'] ?></td>
                            <td><?= $d['nom1'] . ' ' . $d['nom2']  ?></td>
                            <td><?= $d['ape1'] . ' ' . $d['ape2']  ?></td>
                            <td><?= $d['nom_rol'] ?></td>
                            <td><?= $d['correo'] ?></td>
                            <td><?= ($d['estado'] == 1) ? 'Activo' : 'Inactivo'; ?></td>
                            <td>
                                <form action="<?= BASE_URL . 'admin/edit' ?>" method="post">
                                    <input type="hidden" name="id" value="<?= $d['ID_us'] ?>">
                                    <button class="btn btn-circle btn-dark" type="submit" data-bs-toggle="tooltip" data-bs-placement="right" title="Editar usuario">
                                        <i class="fas fa-marker"></i>
                                    </button>
                                </form>

                                <?php //if ($u['usuario']['ID_rol_n'] == 1) {     
                                ?>
                                <a onclick="activarCuenta( <?= $d['ID_us']   ?> )" href="#" class="btn btn-circle btn-success" data-bs-toggle="tooltip" data-bs-placement="right" title="Activar cuenta">
                                    <i class="fas fa-check-square"></i>
                                </a>
                                <a onclick="desactivarCuenta( <?= $d['ID_us']   ?> )" href="#" class="btn btn-circle btn-danger" data-bs-toggle="tooltip" data-bs-placement="right" title="Desactivar cuenta">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                <?php
                    }
                }
                ?>
                </tbody>

            </table>
        </div>
    </div><!-- div de tablas -->
    </div>
    </div><!-- fin de primera divicion -->
    <div class="card card-body col-lg-11 mx-auto my-4 text-center ">
        <h5 class="my-2">Usuarios</h5>
        <div class="row col-lg-10 mx-auto">
            <!-- -------------------------------------------------------------- -->
            <div class=" col-md-4  mx-auto card card-body shadow ">
                <div class="form-group  col-lg-10 row">
                    <label class="col-sm-9" for="">Activos</label>
                    <input class="form-control col-sm-3" type="text" value="<?= $this->datosFijos[1]  ?>" disabled>
                </div>
            </div>

            <div class=" col-md-4  mx-auto card card-body shadow">
                <div class="form-group  col-lg-10 row">
                    <label class="col-sm-9" for="">Inactivos</label>
                    <input class="form-control col-sm-3" type="text" value="<?= $this->datosFijos[2]  ?>" disabled>
                </div>
            </div>

            <div class=" col-md-4  mx-auto card card-body shadow">
                <div class="form-group  col-lg-10 row">
                    <label class="col-sm-9" for="">Registrados</label>
                    <input class="form-control col-sm-3" type="text" value="<?= $this->datosFijos[3]  ?>" disabled>
                </div>
            </div>
            <!-- -------------------------------------------------------------- -->
        </div>
        <div class="card card-body col-md-12 mx-auto my-4 text-center shadow">
            <div class="row">

                <!-- -------------------------------------------------------------- -->

                <div class=" col-md-3 my-2 mx-auto">
                    <a class="btn-block btn btn-dark" href="">Imprimir</a>
                </div>
                <div class=" col-md-3 my-2 mx-auto">
                    <a class="btn-block btn btn-dark" href="">Exportar</a>
                </div>
                <div class=" col-md-3 my-2 mx-auto">
                    <a class="btn-block btn btn-dark" href="formTelefono.php">Directorio telefonico</a>
                </div>
                <div class=" col-md-3 my-2 mx-auto">
                    <a class="btn-block btn btn-dark" href="">Directorio direcciones</a>
                </div>
                <!-- -------------------------------------------------------------- -->
            </div>
        </div>
    </div>
    <?php
    // rutFinFooterFrom();
    //rutFromFin();
    //}  fin de validadcion y ejecucion de permisos por rol
    //
    ?>